### ISSUE TITLE
"HTTP Error Internal Server Error" When Adding New Data Source

### ISSUE THREAD

**Issue by cofonseca** [sbueringer/grafana-consul-datasource#10]
I'm using the latest version of this plugin, as well as the latest version of Grafana. I'm trying to simply add Consul as a data source. I enter my URL as well as a valid ACL token, but when I click Save & Test, I immediately receive an error: "HTTP Error Internal Server Error".

I know my URL is correct because it is the same URL that I use to access the UI or communicate with the API, and I know my token is correct because I can use it to grab data via the API. I've also tried an admin token that has access to everything.

The "Internal Server Error" error is returned immediately. Out of curiosity, I set up a packet sniff on my firewall to look for traffic between my Grafana instance and my Consul cluster, and didn't see any traffic being sent at all. It's as if the plugin isn't even attempting to make a connection.

Here's a screenshot: http://prntscr.com/r1uqom
My installation does not use a custom port so I did not add one here, although I've tried 80. I do not see any errors in my Grafana logs.

Any suggestions on how I can get this working, or is this a bug?

**Comment by cofonseca** [comment]
Apologies... I did actually find a relevant event in the Grafana logs: "Could not find executor for data source type: sbueringer-consul-datasource". I must have missed this before posting.

Following the solution in issue #1 , I was able to fix the error by adding the executable permission to the plugin executable itself. I then restarted my Grafana container and everything began working as expected.

`sudo chmod +x /var/lib/grafana/plugins/sbueringer-grafana-consul-datasource-4226d7b/dist/grafana-consul-plugin_linux_amd64`

I haven't experienced this issue with other plugins which is odd. Perhaps this should be added to the docs? I'll close this out.

**Comment by sbueringer** [comment]
@cofonseca where the other plugins also backend plugins? If yes, can you give me an example?

**Comment by cofonseca** [comment]
@sbueringer the only other data source plugins that I use, aside from the built-in ones, are JSON and BigQuery. I don't recall any permissions issues on these, though.

I was also wondering if you could provide me some additional examples of pulling simple k/v data. I'm trying to pull a single value at a path - a pretty basic scenario. Here's an example of what I'm trying to do:

In Consul, I have a kv value located at "kv/services/example/qa/version". The value of "version" is a simple version number, like "1.6.0". Using the Consul API, if I query "kv/services/example/qa/version?raw=true", it simply returns "1.6.0". I can't seem to figure out how to display this in a singlestat panel though... it just reads "N/A". Any ideas?

In Grafana, my query is as follows:
kv/services/example/qa/version
Format As: Time Series
Type: get value
Legend Format: blank (not quite sure what this does?)

I also tried Table, but I have no idea what to enter for columns.

Sorry for the basic questions, just not really sure where else to find these answers. Happy to help update documentation if I can figure it out. Hope you can help! :)

**Comment by cofonseca** [comment]
Alright, so I was able to resolve that by removing "kv/" from the URL and just starting at "services/". I didn't realize that's how it worked.

Now I get a new error in Grafana: "error generating time series: strconv.ParseFloat: parsing "1.6.0": invalid syntax"

Thoughts? Sorry again for the basic questions, just want to figure out how to get this simple example working properly.

**Comment by sbueringer** [comment]
:). We're doing something like this:
* Text Panel
* get subkeys as tags
* query: kv/services/example/qa
* legen `{{ version }}`

And no problem, just ask here that's fine

The problem is that regular values are parsed and then returned as float. You have to do something like what I did in my example to retrieve text. I know it's a little bit awkward, but the data model of Consul and Grafana weren't really a direct match :)
