### ISSUE TITLE
Share newest plugin releases via grafana.com

### ISSUE THREAD

**Issue by getjack** [sbueringer/grafana-consul-datasource#13]
It seems that the versions 0.1.6 and 0.1.7 are not available through the grafana plugins repository. Even though development seems to be halted I'd like to try out the newer version for other grafana versions to check whether they work or not.

**Comment by sbueringer** [comment]
@getjack 
New plugin version has been published: https://grafana.com/grafana/plugins/sbueringer-consul-datasource
