### ISSUE TITLE
Empty query result

### ISSUE THREAD

**Issue by ngoduykhanh** [sbueringer/grafana-consul-datasource#20]
Hello,

Thanks for creating this plugin. I am giving it a try however it doesn't work as excepted. I've added Consul data source, the connection is working. However, when I make a query, from Grafana's Variables, for example, it shows `None` in the result. 
If I use empty "query", it can list all the key. But when I query to a key, no value returned.
Is there any way to debug it?

I am using the latest Grafana version.

**Comment by sbueringer** [comment]
Hi,

there are a lot of debug logs when you set the Grafana log level via `grafana.ini` to debug

**Comment by sbueringer** [comment]
Hey folks,

I'm going to archive this project as I don't have the bandwith to maintain it anymore. Feel free to fork it :)
