### ISSUE TITLE
Cant install latest version with grafana-cli

### ISSUE THREAD

**Issue by peppermor** [sbueringer/grafana-consul-datasource#29]
Hi,
We have autoprovisioned grafna setup created by Helm chart. Grafna version is 7.5.5 I've added your plugin to list of plugins but installed version is 0.1.5 if I try to enforce 0.2.1 I get: Error: ✗ could not find the version you're looking for .
Plugin is available under https://grafana.com/api/plugins/sbueringer-consul-datasource/versions/0.2.1 but cli cannot see this version

**Comment by norpol** [comment]
I'm having the same issue with a more recent Grafana version. You can workaround with installing directly from GitHub:

```bash
grafana-cli \
        --pluginUrl https://github.com/sbueringer/grafana-consul-datasource/releases/download/v0.2.1/sbueringer-consul-datasource-0.2.1.zip \
        plugins install sbueringer-consul-datasource
```

**Comment by sbueringer** [comment]
Hey folks,

I'm going to archive this project as I don't have the bandwith to maintain it anymore. Feel free to fork it :)
