### ISSUE TITLE
unknown query type: test

### ISSUE THREAD

**Issue by aleskiontherun** [sbueringer/grafana-consul-datasource#39]
Installed 0.2.1 manually, as grafana-cli installs 0.1.5 somehow (see #29). When I'm trying to add a Consul datasource in web UI, I get an error:

>unknown query type: test

Grafana log shows:

>t=2021-09-02T15:36:27+0000 lvl=info msg="Request Completed" logger=context userId=3 orgId=1 uname=xxx method=POST path=/api/tsdb/query status=400 remote_addr=xxx time_ms=8 size=118 referer=https://xxx

Grafana version: 8.1.2

**Comment by sbueringer** [comment]
Hey folks,

I'm going to archive this project as I don't have the bandwith to maintain it anymore. Feel free to fork it :)
