### ISSUE TITLE
alerting

### ISSUE THREAD

**Issue by Gauravshah** [sbueringer/grafana-consul-datasource#4]
Since its a backend plugin would it support alerting, plugin.json doesn't have alert section

**Comment by Gauravshah** [comment]
@sbueringer I am sure this is not the right place. But I have been struggling to move druid plugin to backend. Since you have already created a backend plugin, do you have any resources or documentation that would help ?
I tried building the simple-json-datasource, But it would error out with `executor not found for datasource type` did you come across this issue when building backend plugin

**Comment by sbueringer** [comment]
@Gauravshah No problem :). Sounds like some kind of issue with the datasource id or the plugin.json. Can you give me a link to the current version and what I have to configure in Grafana? Then I'll just try it and see if I have an idea where the problem lies.

**Comment by Gauravshah** [comment]
thanks for the help @sbueringer turn out we had multiple versions of same library. one inside `grafana_plugin_model/vendor` and other inside the `simple-json/vendor` . Removing one of them fixed the issue thanks.

**Comment by travis-bear** [comment]
Alerting is one of Grafana's core features.  Health checks are one of Consul's core features.  These two features are very closely related.  Having access to Consul's health check data in Grafana would be very valuable.

**Comment by sbueringer** [comment]
Hey folks,

I'm going to archive this project as I don't have the bandwith to maintain it anymore. Feel free to fork it :)
