### ISSUE TITLE
Allow access without token

### ISSUE THREAD

**Issue by dmke** [sbueringer/grafana-consul-datasource#5]
We're running a small cluster of Consul nodes in a private network (as in RFC1918), and therefore we don't have a need for ACLs.

Is it possible to make the ACL token optional? In https://github.com/sbueringer/grafana-consul-datasource/issues/3#issuecomment-453831373 you wrote:

> I actually never thought of running Consul without token. But I guess it's possible? Then I think nothing speaks against supporting that.

I'd like to make a PR for that, but after glancing over the sources, I'm afraid I don't know where to start :-)

**Comment by dmke** [comment]
FYI, we've found a workaround which works without Grafana.

Our use case would've been to get some variables out of Consul to influence some Prometheus graphs. We've rewritten our exporter so that we now can get the same values with a Prometheus-sourced variable and the `label_values($metric_name, $label_name)` expression.

I'm leaving this open (if others find interest in this issue), but I'm deactivating notifications. Feel free to @mention me, if you've any questions, though.

**Comment by sbueringer** [comment]
Then I leave it like that for now. If anybody else shows interest, I'll be open for PRs or might implement it myself.

**Comment by mozai** [comment]
Consul has a default token for anonymous access [took me a while to find it in the official documentation](https://www.consul.io/docs/agent/acl-system.html#acl-tokens).
What happens if you use `00000000-0000-0000-0000-000000000002` as the token?

**Comment by lars-nielsen** [comment]
@mozai @dmke 

We have the same setup (ACL's disabled)

i've just tried with 00000000-0000-0000-0000-000000000002 as token, and it couldn't pass the test.

I looks like it works even though the UI is complaining "HTTP Error Bad Request" with a blank token. I am able to create variables with consul as a datastore

**Comment by sbueringer** [comment]
@lars-nielsen Can you try "anonymous" as token?

**Comment by lars-nielsen** [comment]
@sbueringer 

"anonymous" returns HTTP Error Bad Request, is there any way to see what is sent to consul

**Comment by domgoodwin** [comment]
Hi @sbueringer , was this ever look at further. I'm hitting an issue where I've got consul acl's disabled and the mandatory ACL field isn't allowing this plugin to talk to consul

**Comment by domgoodwin** [comment]
From my testing I've found the anonymous flag works for using anonymous with consul ACLs enabled however you still need them enabled. Ideally if you don't supply a token it doesn't call the ACL endpoint and works normally

**Comment by sbueringer** [comment]
Hi @domgoodwin, unfortunately I didn't have time to investigate this further. If you find a way how I can create a client without using tokens [here](https://github.com/sbueringer/grafana-consul-datasource/blob/master/datasource.go#L389-L406). I can implement it. I don't really have the time right now to play around with Consul, as our Consul is configured with ACLs enabled

**Comment by GhostNr1** [comment]
We have the same problem that we run in a private network without ACL enabled so this would be a great feature

**Comment by acarsercan** [comment]
+1

**Comment by ryzhovas** [comment]
+1

**Comment by ep4eg** [comment]
> Hi @domgoodwin, unfortunately I didn't have time to investigate this further. If you find a way how I can create a client without using tokens [here](https://github.com/sbueringer/grafana-consul-datasource/blob/master/datasource.go#L389-L406). I can implement it. I don't really have the time right now to play around with Consul, as our Consul is configured with ACLs enabled

As per documentation, it's enough not to override the default token. You simply need to check if a token was provided by user in your code.
https://godoc.org/github.com/hashicorp/consul/api#Config

**Comment by sbueringer** [comment]
@ep4eg Thx for the info. I implemented and tested it. Looks like it works now. It can be tested e.g. via:
```bash
docker run --rm -it -p 3000:3000 --name=grafana --net=host  \
   -e "GF_INSTALL_PLUGINS=https://github.com/sbueringer/grafana-consul-datasource/releases/download/v0.1.8/grafana-consul-datasource-v0.1.8.zip;sbueringer-consul-datasource" \
   -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=sbueringer-consul-datasource" grafana/grafana
```

**Comment by sbueringer** [comment]
I released a new version of the plugin which supports this (just leave the consul token empty in the config menu):
https://grafana.com/grafana/plugins/sbueringer-consul-datasource
