### ISSUE TITLE
readme needs a 'requirements' section

### ISSUE THREAD

**Issue by mozai** [sbueringer/grafana-consul-datasource#6]
I feel you should mention in the Readme.md what are the prerequisites for your software: minimum compatible Grafana version, minimum compatible Consul version.  i.e.: if you will always send an API token with every request, it needs Consul v 1.4.x or above.

**Comment by sbueringer** [comment]
I can add a section with requirements. Currently I'm using Grafana 5 and Consul 1.2.2. I'm not sure what's the reason that Consul v1.4.x is required as it works perfectly with Consul v1.2?

**Comment by sbueringer** [comment]
The newly published version 0.2.1 of the plugin now requires Grafana 7.3. This dependency is specified in the `src/plugin.json` file.
I'm not sure how Grafana handles/shows this information. 

Regarding Consul: It's now possible to also avoid sending a token if authentication is disabled. As the current plugin should work with almost all Consul versions of the last few years and I'm not sure on which exactly, I'm unable to document specific supported version.

I updated the README.md with this information
