### ISSUE TITLE
"Plugin unavailable" log, "Metric request error" on Grafana 8.3 with consul datasource 4.2.1

### ISSUE THREAD

**Issue by mike-sol** [sbueringer/grafana-consul-datasource#60]
Hey there,

I have managed to install the Consul data source with this Docker env var:
```
 GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS="sbueringer-consul-datasource" 
```

However, even though the plugin seems to load in the Data Source UI, every time I try to hit my HTTPS (with a standard, public-CA certificate from Amazon ACM) ACL-verified Consul endpoint, I get the error "Metric request error" when I hit "Save and Test".

I can docker exec my way into the container and curl the endpoint address I am aiming at.

In the Grafana logs, there is an entry generated that says "plugin unavailable". It seems to be installed though, as I can see the configuration screen.

What might I be doing wrong?

**Comment by sbueringer** [comment]
Not sure, to be honest I didn't use the plugin myself for 1-2 years.

**Comment by sbueringer** [comment]
Hey folks,

I'm going to archive this project as I don't have the bandwith to maintain it anymore. Feel free to fork it :)
