### ISSUE TITLE
Seems this plugin does not support multiple dc

### ISSUE THREAD

**Issue by ybiconviva** [sbueringer/grafana-consul-datasource#7]
My consul is enabled with multiple data center, how I can pass the data center ?dc=dc1 in the query

**Comment by sbueringer** [comment]
Hm currently not implemented. I guess there are multiple ways to implement it.

Ether add a flag for this n the query or add a property to the datasource configuration, but then it would be necessary to configure a datasource per datacenter

**Comment by travis-bear** [comment]
Many enterprises operate Consul across multiple datacenters.  Having this would be valuable.

**Comment by sbueringer** [comment]
I'm open to contributions

**Comment by sbueringer** [comment]
If I see correctly, I probably only have to set the datacenter in the used consul client:
https://github.com/hashicorp/consul/blob/master/api/api.go#L88

@travis-bear @ybiconviva do you know if that's enough?
If you're interested, I can open a PR for it, but somebody would have to test if it works.

**Comment by sbueringer** [comment]
Hey folks,

I'm going to archive this project as I don't have the bandwith to maintain it anymore. Feel free to fork it :)
